--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/raima/wallpapers/cool.jpg"

-- Special
background="#090a11"
foreground="#e5ccc6"
cursor="#e5ccc6"

-- Colors
color0="#090a11"
color1="#62667A"
color2="#5F6982"
color3="#737489"
color4="#8B7D80"
color5="#827E92"
color6="#9B8B9C"
color7="#e5ccc6"
color8="#a08e8a"
color9="#62667A"
color10="#5F6982"
color11="#737489"
color12="#8B7D80"
color13="#827E92"
color14="#9B8B9C"
color15="#e5ccc6"
