# Shell variables
# Generated by 'wal'
wallpaper='/home/raima/wallpapers/cool.jpg'

# Special
background='#090a11'
foreground='#e5ccc6'
cursor='#e5ccc6'

# Colors
color0='#090a11'
color1='#62667A'
color2='#5F6982'
color3='#737489'
color4='#8B7D80'
color5='#827E92'
color6='#9B8B9C'
color7='#e5ccc6'
color8='#a08e8a'
color9='#62667A'
color10='#5F6982'
color11='#737489'
color12='#8B7D80'
color13='#827E92'
color14='#9B8B9C'
color15='#e5ccc6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
